.data

# level 1. just a normal level.
level_1:
	.ascii "########################################"
	.ascii "#     ~~#   #^^^#  ~~........###########"
	.ascii "# $   ~ #b  #^^^#   ~~~####......#    ##"
	.ascii "#       #...#...#     ~~######    o   ##"
	.ascii "#^                    ~ ######    oob ##"
	.ascii "#^^                   ~ ################"
	.ascii "#^^^                                  %#"
	.ascii "########    .......                    #"
	.ascii "#      o    ........    #####          #"
	.ascii "#    b o   ...   ...    #^^ ~          #"
	.ascii "#b ^^  o  ....b  .....  #^^ ~          #"
	.ascii "########################################"
	.ascii "########################################"
	.ascii "########################################"
	.ascii "########################################"
	.ascii "########################################"
	.ascii "########################################"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "########################################"

# for testing dirt digging and placement.
test_level_dirt:
	.ascii "########################################"
	.ascii "#                                      #"
	.ascii "# $  .  .  .  .                        #"
	.ascii "#                                      #"
	.ascii "#^o  ..........                        #"
	.ascii "###  .                                 #"
	.ascii "#    .                                 #"
	.ascii "#    .                                 #"
	.ascii "#    .                                 #"
	.ascii "#    .                                 #"
	.ascii "#    .                                 #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "########################################"

# for testing diamond objects.
test_level_diamonds:
	.ascii "########################################"
	.ascii "#                                      #"
	.ascii "# $  ^  ^  ^                           #"
	.ascii "#    #  .  ^                           #"
	.ascii "#       #  ^                           #"
	.ascii "#          ^                           #"
	.ascii "#          .                           #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "########################################"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "########################################"

# for testing vine tiles (how they push the player back).
test_level_vines:
	.ascii "########################################"
	.ascii "#                                      #"
	.ascii "# $  ~  ~~~   ^                        #"
	.ascii "#         ~   .                        #"
	.ascii "#         ~   ~                        #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "########################################"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "########################################"

# for testing boulder objects.
test_level_boulders:
	.ascii "########################################"
	.ascii "#                                      #"
	.ascii "# $  o  o  o   oo   o # o              #"
	.ascii "#    #  .  o   ##   #####              #"
	.ascii "#       #  o                           #"
	.ascii "#          o                           #"
	.ascii "#          .                           #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "########################################"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "########################################"

# for testing the goal tile.
test_level_goal:
	.ascii "########################################"
	.ascii "#                                      #"
	.ascii "# $  %                                 #"
	.ascii "# ^                                    #"
	.ascii "###                                    #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "########################################"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "########################################"

# for testing bug movement behaviors.
test_level_bug_movement:
	.ascii "########################################"
	.ascii "#     # #   #                          #"
	.ascii "#b  $ # #   #                          #"
	.ascii "#     # #   #                          #"
	.ascii "#         ###                          #"
	.ascii "###         #                          #"
	.ascii "#         ###                          #"
	.ascii "###         #                          #"
	.ascii "#   #  #    #                          #"
	.ascii "#   #  #    #                          #"
	.ascii "#############                          #"
	.ascii "###                                    #"
	.ascii "#b#  #b   b                            #"
	.ascii "###                                    #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "########################################"

# for testing bug vine-eating behavior.
test_level_bug_vines:
	.ascii "########################################"
	.ascii "#  ~~~#~~~~~#                          #"
	.ascii "#b$  ~#~~~~~#                          #"
	.ascii "#    ~#~   ~#                          #"
	.ascii "#   b ~    ~#                          #"
	.ascii "#          ~#                          #"
	.ascii "#          ~#                          #"
	.ascii "#     #~~~~~#                          #"
	.ascii "#     #^^^^^#                          #"
	.ascii "#     #^^^^^#                          #"
	.ascii "########################################"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "########################################"

# for testing bugs reaching the goal.
test_level_bug_goal:
	.ascii "########################################"
	.ascii "#           #                          #"
	.ascii "#b$        %#                          #"
	.ascii "#           #                          #"
	.ascii "#           #                          #"
	.ascii "#           #                          #"
	.ascii "#           #                          #"
	.ascii "#           #                          #"
	.ascii "#           #                          #"
	.ascii "#           #                          #"
	.ascii "########################################"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "########################################"

# blank test level for copying and pasting to make new levels if you like.
# BUT DON'T PUT THEM IN THIS FILE! Because you aren't turning this file in.
test_level_blank:
	.ascii "########################################"
	.ascii "#                                      #"
	.ascii "# $                                    #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "#                                      #"
	.ascii "########################################"

.text